server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
